### Datos faltantes: análisis inicial

Identificación de columnas con valores nulos y su posible relación con otras variables.

In [77]:
import pandas as pd 
import numpy as np
from IPython.display import display
import sys, os
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
%matplotlib inline
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
#from functions.transformers import *

In [78]:
df_train_raw = pd.read_csv('../data/raw/train.csv').drop('Id', axis=1)
df_train = df_train_raw.copy()
print(f'start dimensions: {df_train.shape}')
df_train.head()

start dimensions: (1460, 80)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [79]:
missing_data = df_train.isnull().sum()
missing_data = pd.DataFrame(missing_data[missing_data > 0], columns=['missing counts'])
missing_data['percentage'] = np.round(missing_data['missing counts'] / df_train.shape[0] * 100, 2)
missing_data = missing_data.sort_values(by='percentage', ascending=True)
missing_data

              missing counts  percentage
Electrical                 1        0.07
MasVnrArea                 8        0.55
BsmtCond                  37        2.53
BsmtFinType1              37        2.53
BsmtQual                  37        2.53
BsmtExposure              38        2.60
BsmtFinType2              38        2.60
GarageType                81        5.55
GarageQual                81        5.55
GarageFinish              81        5.55
GarageCond                81        5.55
GarageYrBlt               81        5.55
LotFrontage              259       17.74
FireplaceQu              690       47.26
MasVnrType               872       59.73
Fence                   1179       80.75
Alley                   1369       93.77
MiscFeature             1406       96.30
PoolQC                  1453       99.52

In [85]:
#Electrical: Sistema eléctrico.
print('----'*20)
features_electical = ['Heating', 'HeatingQC', 'CentralAir', 'Electrical']
res_electrical = df_train.groupby(features_electical)['Electrical'].agg(['count', 'nunique'])
res_electrical

df_train[df_train['Heating'] == 'GasA' | df_train['HeatingQC'] == 'Ex']

--------------------------------------------------------------------------------

TypeError: Cannot perform 'ror_' with a dtyped [object] array and scalar of type [bool]