In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import probplot, mannwhitneyu
from IPython.display import display as dsp
%matplotlib inline
os.chdir('..')
from functions.missingvalues.listMissingValues import list_missing_values

df = pd.read_csv("./data/raw/train.csv")
use_df = df.copy()

In [2]:
print(df.shape)
list_missing_values(use_df)

(1460, 81)

              missing counts  percentage(%)     type
PoolQC                  1453          99.52      str
MiscFeature             1406          96.30      str
Alley                   1369          93.77      str
Fence                   1179          80.75      str
MasVnrType               872          59.73      str
FireplaceQu              690          47.26      str
LotFrontage              259          17.74  float64
GarageType                81           5.55      str
GarageYrBlt               81           5.55  float64
GarageFinish              81           5.55      str
GarageQual                81           5.55      str
GarageCond                81           5.55      str
BsmtExposure              38           2.60      str
BsmtFinType2              38           2.60      str
BsmtQual                  37           2.53      str
BsmtCond                  37           2.53      str
BsmtFinType1              37           2.53      str
MasVnrArea                 8           0.55  float64
Electrical                 1           0.07      str

In [3]:
""" 
#PoolQC: Calidad de la piscina.
Ex	Excellent (Excelente)
Gd	Good (Bueno)
TA	Average/Typical (Promedio/Típico)
Fa	Fair (Justo/Regular)
NA	No Pool (Sin piscina)
"""
from functions.missingvalues.mannWhitney_u import MannWhitneyU
use_df['PoolQC'].unique()

mw = MannWhitneyU(use_df)
mw.all_features(missing_feature="PoolQC", desc=True)

,reference_feature,stat,p_value,cohen_s,cohen_s_interpretation,rho_interpretation,rho,p_value_rho,evidence_MAR,p_value_interpretation
32,PoolArea,10171.0,0.00000,-99.84428,Fuerte (Negativa),Fuerte (Negativa),-1.00000,0.00000,True,perfect!!
2,LotArea,8678.0,0.00125,-1.26583,Prácticamente nula (Negativa),Prácticamente nula (Negativa),-0.08452,0.00123,True,high
23,Fireplaces,8288.0,0.00135,-1.50135,Prácticamente nula (Negativa),Prácticamente nula (Negativa),-0.08394,0.00133,True,high
1,LotFrontage,6066.0,0.00338,-3.25926,Prácticamente nula (Negativa),Fuerte (Sin correlación),NaN,NaN,True,high
20,BedroomAbvGr,7838.5,0.00615,-1.04669,Prácticamente nula (Negativa),Prácticamente nula (Negativa),-0.07174,0.00610,True,high
12,1stFlrSF,8086.0,0.00702,-2.14590,Prácticamente nula (Negativa),Prácticamente nula (Negativa),-0.07059,0.00697,True,high
16,BsmtFullBath,7605.0,0.00820,-1.11569,Prácticamente nula (Negativa),Prácticamente nula (Negativa),-0.06923,0.00814,True,high
15,GrLivArea,7993.0,0.00899,-2.79049,Prácticamente nula (Negativa),Prácticamente nula (Negativa),-0.06840,0.00894,True,high
9,BsmtFinSF2,6685.5,0.00930,-0.62695,Prácticamente nula (Negativa),Prácticamente nula (Negativa),-0.06812,0.00923,True,high
14,LowQualFinSF,5727.0,0.01192,-1.03880,Prácticamente nula (Negativa),Prácticamente nula (Negativa),-0.06588,0.01181,True,moderate
13,2ndFlrSF,7449.0,0.01880,-1.30839,Prácticamente nula (Negativa),Prácticamente nula (Negativa),-0.06152,0.01873,True,moderate
22,TotRmsAbvGrd,7561.5,0.02307,-1.36341,Prácticamente nula (Negativa),Prácticamente nula (Negativa),-0.05950,0.02299,True,moderate
36,SalePrice,7569.0,0.02566,-1.36165,Prácticamente nula (Negativa),Prácticamente nula (Negativa),-0.05843,0.02558,True,moderate
35,YrSold,2672.0,0.02653,0.83445,Prácticamente nula (Positiva),Prácticamente nula (Positiva),0.05809,0.02645,True,moderate
8,BsmtFinSF1,7499.0,0.02747,-2.43937,Prácticamente nula (Negativa),Prácticamente nula (Negativa),-0.05773,0.02739,True,moderate
3,OverallQual,7439.0,0.03010,-1.07213,Prácticamente nula (Negativa),Prácticamente nula (Negativa),-0.05679,0.03002,True,moderate