In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import probplot, mannwhitneyu
from IPython.display import display as dsp
%matplotlib inline
os.chdir('..')
from functions.missingvalues.listMissingValues import list_missing_values

df = pd.read_csv("./data/raw/train.csv")
use_df = df.copy()

In [2]:
print(df.shape)
list_missing_values(use_df)

(1460, 81)

              missing counts  percentage(%)     type
PoolQC                  1453          99.52      str
MiscFeature             1406          96.30      str
Alley                   1369          93.77      str
Fence                   1179          80.75      str
MasVnrType               872          59.73      str
FireplaceQu              690          47.26      str
LotFrontage              259          17.74  float64
GarageType                81           5.55      str
GarageYrBlt               81           5.55  float64
GarageFinish              81           5.55      str
GarageQual                81           5.55      str
GarageCond                81           5.55      str
BsmtExposure              38           2.60      str
BsmtFinType2              38           2.60      str
BsmtQual                  37           2.53      str
BsmtCond                  37           2.53      str
BsmtFinType1              37           2.53      str
MasVnrArea                 8           0.55  float64
Electrical                 1           0.07      str

In [3]:
""" 
#PoolQC: Calidad de la piscina.
Ex	Excellent (Excelente)
Gd	Good (Bueno)
TA	Average/Typical (Promedio/Típico)
Fa	Fair (Justo/Regular)
NA	No Pool (Sin piscina)
"""
from functions.missingvalues import MannWhitneyU
use_df['PoolQC'].unique()

mw = MannWhitneyU(use_df)
resmw = mw.all_features(missing_feature="PoolQC", desc=True)
dsp(resmw)

,reference_feature,stat,p_value,cohen_s,rho,p_value_interpretation,cohen_s_interpretation,rho_interpretation,p_value_rho
0,PoolArea,10171.0,0.00000,-99.84428,-1.00000,perfect!!,Grande (Negativa),Muy fuerte (Negativa),0.00000
1,LotArea,8678.0,0.00125,-1.26583,-0.08452,high,Grande (Negativa),Insignificante (Negativa),0.00123
2,Fireplaces,8288.0,0.00135,-1.50135,-0.08394,high,Grande (Negativa),Insignificante (Negativa),0.00133
3,LotFrontage,6066.0,0.00338,-3.25926,-0.08461,high,Grande (Negativa),Insignificante (Negativa),0.00334
4,BedroomAbvGr,7838.5,0.00615,-1.04669,-0.07174,high,Grande (Negativa),Insignificante (Negativa),0.00610
5,1stFlrSF,8086.0,0.00702,-2.14590,-0.07059,high,Grande (Negativa),Insignificante (Negativa),0.00697
6,BsmtFullBath,7605.0,0.00820,-1.11569,-0.06923,high,Grande (Negativa),Insignificante (Negativa),0.00814
7,GrLivArea,7993.0,0.00899,-2.79049,-0.06840,high,Grande (Negativa),Insignificante (Negativa),0.00894
8,BsmtFinSF2,6685.5,0.00930,-0.62695,-0.06812,high,Moderado (Negativa),Insignificante (Negativa),0.00923
9,LowQualFinSF,5727.0,0.01192,-1.03880,-0.06588,moderate,Grande (Negativa),Insignificante (Negativa),0.01181
10,2ndFlrSF,7449.0,0.01880,-1.30839,-0.06152,moderate,Grande (Negativa),Insignificante (Negativa),0.01873
11,TotRmsAbvGrd,7561.5,0.02307,-1.36341,-0.05950,moderate,Grande (Negativa),Insignificante (Negativa),0.02299
12,SalePrice,7569.0,0.02566,-1.36165,-0.05843,moderate,Grande (Negativa),Insignificante (Negativa),0.02558
13,YrSold,2672.0,0.02653,0.83445,0.05809,moderate,Grande (Positiva),Insignificante (Positiva),0.02645
14,BsmtFinSF1,7499.0,0.02747,-2.43937,-0.05773,moderate,Grande (Negativa),Insignificante (Negativa),0.02739
15,OverallQual,7439.0,0.03010,-1.07213,-0.05679,moderate,Grande (Negativa),Insignificante (Negativa),0.03002

In [4]:
from functions.missingvalues import NormalDistributionTest
df["feature_normal"] = np.random.normal(0, 1, 1460)
checkNormal = NormalDistributionTest(df)

In [5]:
res = checkNormal.shapiro_wilk_test()
dsp(res)
res = checkNormal.jarque_bera_test()
dsp(res)

,name_feature,shapiro_stat,p_value,evidence_non_normality,interpretacion
0,MSSubClass,0.80457,0.00000,True,No normal
1,LotFrontage,0.88040,0.00000,True,No normal
2,LotArea,0.35106,0.00000,True,No normal
3,OverallQual,0.94801,0.00000,True,No normal
4,OverallCond,0.82892,0.00000,True,No normal
5,YearBuilt,0.92560,0.00000,True,No normal
6,YearRemodAdd,0.86280,0.00000,True,No normal
7,MasVnrArea,0.63929,0.00000,True,No normal
8,BsmtFinSF1,0.84796,0.00000,True,No normal
9,BsmtFinSF2,0.32728,0.00000,True,No normal
10,BsmtUnfSF,0.93042,0.00000,True,No normal
11,TotalBsmtSF,0.91735,0.00000,True,No normal
12,1stFlrSF,0.92695,0.00000,True,No normal
13,2ndFlrSF,0.76680,0.00000,True,No normal
14,LowQualFinSF,0.09799,0.00000,True,No normal
15,GrLivArea,0.92798,0.00000,True,No normal
16,BsmtFullBath,0.65830,0.00000,True,No normal
17,BsmtHalfBath,0.24291,0.00000,True,No normal
18,FullBath,0.71936,0.00000,True,No normal
19,HalfBath,0.63800,0.00000,True,No normal
20,BedroomAbvGr,0.84980,0.00000,True,No normal
21,KitchenAbvGr,0.21980,0.00000,True,No normal
22,TotRmsAbvGrd,0.94228,0.00000,True,No normal
23,Fireplaces,0.75523,0.00000,True,No normal
24,GarageYrBlt,0.92094,0.00000,True,No normal
25,GarageCars,0.83537,0.00000,True,No normal
26,GarageArea,0.97533,0.00000,True,No normal
27,WoodDeckSF,0.76852,0.00000,True,No normal
28,OpenPorchSF,0.72717,0.00000,True,No normal
29,EnclosedPorch,0.41444,0.00000,True,No normal
30,3SsnPorch,0.09493,0.00000,True,No normal
31,ScreenPorch,0.29821,0.00000,True,No normal
32,PoolArea,0.04120,0.00000,True,No normal
33,MiscVal,0.05823,0.00000,True,No normal
34,MoSold,0.96878,0.00000,True,No normal
35,YrSold,0.89710,0.00000,True,No normal
36,SalePrice,0.86967,0.00000,True,No normal
37,feature_normal,0.99910,0.70915,False,Normal

,name_feature,jarque_bera_stat,p_value,evidence_non_normality,interpretacion
0,MSSubClass,6.312509e+02,0.00000,True,No normal
1,LotFrontage,1.604228e+04,0.00000,True,No normal
2,LotArea,2.531815e+06,0.00000,True,No normal
3,OverallCond,1.900538e+02,0.00000,True,No normal
4,YearRemodAdd,1.600036e+02,0.00000,True,No normal
5,YearBuilt,1.032796e+02,0.00000,True,No normal
6,MasVnrArea,7.823323e+03,0.00000,True,No normal
7,BsmtFinSF1,8.152890e+03,0.00000,True,No normal
8,1stFlrSF,2.452095e+03,0.00000,True,No normal
9,BsmtFinSF2,2.882882e+04,0.00000,True,No normal
10,BsmtUnfSF,2.190501e+02,0.00000,True,No normal
11,TotalBsmtSF,1.116546e+04,0.00000,True,No normal
12,LowQualFinSF,4.382541e+05,0.00000,True,No normal
13,2ndFlrSF,1.793011e+02,0.00000,True,No normal
14,GrLivArea,1.898795e+03,0.00000,True,No normal
15,BsmtFullBath,1.292358e+02,0.00000,True,No normal
16,GarageYrBlt,1.069113e+02,0.00000,True,No normal
17,BsmtHalfBath,2.032396e+04,0.00000,True,No normal
18,FullBath,4.513061e+01,0.00000,True,No normal
19,HalfBath,1.815435e+02,0.00000,True,No normal
20,BedroomAbvGr,3.104697e+02,0.00000,True,No normal
21,KitchenAbvGr,3.289370e+04,0.00000,True,No normal
22,TotRmsAbvGrd,1.575120e+02,0.00000,True,No normal
23,Fireplaces,1.054203e+02,0.00000,True,No normal
24,OpenPorchSF,5.708503e+03,0.00000,True,No normal
25,GarageCars,3.133581e+01,0.00000,True,No normal
26,GarageArea,5.822260e+01,0.00000,True,No normal
27,WoodDeckSF,1.116652e+03,0.00000,True,No normal
28,3SsnPorch,9.496542e+05,0.00000,True,No normal
29,EnclosedPorch,8.886720e+03,0.00000,True,No normal
30,ScreenPorch,2.465920e+04,0.00000,True,No normal
31,PoolArea,3.065038e+06,0.00000,True,No normal
32,YrSold,8.848837e+01,0.00000,True,No normal
33,MiscVal,2.983478e+07,0.00000,True,No normal
34,SalePrice,3.438872e+03,0.00000,True,No normal
35,MoSold,2.098810e+01,0.00003,True,No normal
36,OverallQual,1.194216e+01,0.00255,True,No normal
37,feature_normal,1.234630e+00,0.53939,False,Normal