In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display as dsp
%matplotlib inline
os.chdir('..')

df = pd.read_csv("./data/raw/train.csv")
use_df = df.copy()

In [2]:
from functions.utilsMethods import UtilsMethods
print(df.shape)

utils = UtilsMethods(use_df)
features_missing_values = utils.createFeaturesMissingValuesList()

(1460, 81)

              missing counts  percentage(%)     type
PoolQC                  1453          99.52      str
MiscFeature             1406          96.30      str
Alley                   1369          93.77      str
Fence                   1179          80.75      str
MasVnrType               872          59.73      str
FireplaceQu              690          47.26      str
LotFrontage              259          17.74  float64
GarageType                81           5.55      str
GarageYrBlt               81           5.55  float64
GarageFinish              81           5.55      str
GarageQual                81           5.55      str
GarageCond                81           5.55      str
BsmtExposure              38           2.60      str
BsmtFinType2              38           2.60      str
BsmtQual                  37           2.53      str
BsmtCond                  37           2.53      str
BsmtFinType1              37           2.53      str
MasVnrArea                 8           0.55  float64
Electrical                 1           0.07      str

In [3]:
from functions.numeric_missing_correlations import NumericMissingCorrelations
nmc = NumericMissingCorrelations(dataFrame=use_df)
res = nmc.mannWhitneyU(featureMissingValues="PoolQC")
res = res.apply(lambda x: x.round(4))
res[res["evidence_MAR"]]

         feature    stat  p_value  evidence_MAR
1    LotFrontage  1104.0   0.0034          True
2        LotArea  1493.0   0.0012          True
3    OverallQual  2732.0   0.0301          True
8     BsmtFinSF1  2672.0   0.0275          True
9     BsmtFinSF2  3485.5   0.0093          True
12      1stFlrSF  2085.0   0.0070          True
13      2ndFlrSF  2722.0   0.0188          True
14  LowQualFinSF  4444.0   0.0119          True
15     GrLivArea  2178.0   0.0090          True
16  BsmtFullBath  2566.0   0.0082          True
20  BedroomAbvGr  2332.5   0.0061          True
22  TotRmsAbvGrd  2609.5   0.0231          True
23    Fireplaces  1883.0   0.0013          True
32      PoolArea     0.0   0.0000          True
35        YrSold  7499.0   0.0265          True
36     SalePrice  2602.0   0.0257          True

In [4]:
""" 
PoolQC: Calidad de la piscina.

Ex	Excellent (Excelente)
Gd	Good (Bueno)
TA	Average/Typical (Promedio/Típico)
Fa	Fair (Justo/Regular)
NA	No Pool (Sin piscina)
"""
uniques = use_df["PoolQC"].unique()
print(uniques)

nmc.mannWhitneyU(featureMissingValues="PoolQC")

<StringArray>
[nan, 'Ex', 'Fa', 'Gd']
Length: 4, dtype: str

          feature    stat   p_value  evidence_MAR
0      MSSubClass  3714.0  0.203913         False
1     LotFrontage  1104.0  0.003384          True
2         LotArea  1493.0  0.001247          True
3     OverallQual  2732.0  0.030103          True
4     OverallCond  5307.0  0.825785         False
5       YearBuilt  4702.0  0.730657         False
6    YearRemodAdd  4962.0  0.911868         False
7      MasVnrArea  4871.5  0.850559         False
8      BsmtFinSF1  2672.0  0.027469          True
9      BsmtFinSF2  3485.5  0.009296          True
10      BsmtUnfSF  6651.0  0.159505         False
11    TotalBsmtSF  3078.5  0.071365         False
12       1stFlrSF  2085.0  0.007019          True
13       2ndFlrSF  2722.0  0.018804          True
14   LowQualFinSF  4444.0  0.011921          True
15      GrLivArea  2178.0  0.008992          True
16   BsmtFullBath  2566.0  0.008199          True
17   BsmtHalfBath  4643.5  0.319809         False
18       FullBath  3511.5  0.106223         False
19       HalfBath  4104.0  0.294182         False
20   BedroomAbvGr  2332.5  0.006150          True
21   KitchenAbvGr  5316.5  0.570387         False
22   TotRmsAbvGrd  2609.5  0.023068          True
23     Fireplaces  1883.0  0.001348          True
24    GarageYrBlt  5085.5  0.787660         False
25     GarageCars  4255.5  0.405206         False
26     GarageArea  3278.0  0.104356         False
27     WoodDeckSF  3111.5  0.055590         False
28    OpenPorchSF  3588.0  0.158307         False
29  EnclosedPorch  4980.0  0.876626         False
30      3SsnPorch  5169.5  0.733337         False
31    ScreenPorch  4705.0  0.466507         False
32       PoolArea     0.0  0.000000          True
33        MiscVal  4517.5  0.112208         False
34         MoSold  6072.5  0.371843         False
35         YrSold  7499.0  0.026529          True
36      SalePrice  2602.0  0.025659          True