In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import probplot, mannwhitneyu
from IPython.display import display as dsp
%matplotlib inline
os.chdir('..')
from functions.listMissingValues import list_missing_values

df = pd.read_csv("./data/raw/train.csv")
use_df = df.copy()

In [2]:
print(df.shape)
list_missing_values(use_df)

(1460, 81)

              missing counts  percentage(%)     type
PoolQC                  1453          99.52      str
MiscFeature             1406          96.30      str
Alley                   1369          93.77      str
Fence                   1179          80.75      str
MasVnrType               872          59.73      str
FireplaceQu              690          47.26      str
LotFrontage              259          17.74  float64
GarageType                81           5.55      str
GarageYrBlt               81           5.55  float64
GarageFinish              81           5.55      str
GarageQual                81           5.55      str
GarageCond                81           5.55      str
BsmtExposure              38           2.60      str
BsmtFinType2              38           2.60      str
BsmtQual                  37           2.53      str
BsmtCond                  37           2.53      str
BsmtFinType1              37           2.53      str
MasVnrArea                 8           0.55  float64
Electrical                 1           0.07      str

In [3]:
"""
#PoolQC: Calidad de la piscina.
Ex	Excellent (Excelente)
Gd	Good (Bueno)
TA	Average/Typical (Promedio/Típico)
Fa	Fair (Justo/Regular)
NA	No Pool (Sin piscina)
"""

from functions.numeric_missing_correlations import NumericMissingCorrelations

nmc = NumericMissingCorrelations(use_df)
nmc.mannWhitneyU(featureMissingValues="PoolQC", featuresReference=["PoolArea", "LotArea"])

    feature    stat  p_value
0  PoolArea     0.0  0.00000
1   LotArea  1493.0  0.00125

In [5]:
from functions.categorical_missing_correlations import CategoricalMissingCorrelations

cmc = CategoricalMissingCorrelations(use_df)
cmc.chi2("PoolQC", ["FireplaceQu", "MasVnrType"])

Empty DataFrame
Columns: [feature, stat, p_value, dof, expected]
Index: []