In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import probplot, mannwhitneyu
from IPython.display import display as dsp
%matplotlib inline
import sys, os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
from functions.eda_functions import test_mcar, list_missing_values, HypothesisTestNumeric
PATH_DATASET = "../data/raw/train.csv"
df = pd.read_csv(PATH_DATASET)
print("dimensiones del dataset:", df.shape)
#display(df.head())

dimensiones del dataset: (1460, 81)

In [2]:
list_missing_values(df)

              missing counts  percentage(%)
PoolQC                  1453          99.52
MiscFeature             1406          96.30
Alley                   1369          93.77
Fence                   1179          80.75
MasVnrType               872          59.73
FireplaceQu              690          47.26
LotFrontage              259          17.74
GarageType                81           5.55
GarageYrBlt               81           5.55
GarageFinish              81           5.55
GarageQual                81           5.55
GarageCond                81           5.55
BsmtExposure              38           2.60
BsmtFinType2              38           2.60
BsmtQual                  37           2.53
BsmtCond                  37           2.53
BsmtFinType1              37           2.53
MasVnrArea                 8           0.55
Electrical                 1           0.07

In [3]:
#PoolQC: Calidad de la piscina.
from functions.eda_functions import ApplyNumericTest


dsp(df['PoolQC'].unique())
numericPoolTest = ApplyNumericTest(df, missingFeature="PoolQC", onlyTrue=True)
resTest = numericPoolTest.mann_whitney_u()
dsp(resTest.head(5))

<StringArray>
[nan, 'Ex', 'Fa', 'Gd']
Length: 4, dtype: str

,name_feature,mann_whitney_u,p_value,evidence_MAR,cohen_d,spearman_rho,spearman_p_value
32,PoolArea,10171.0,0.00000,True,99.84,-1.00,0.00
2,LotArea,8678.0,0.00125,True,1.27,-0.08,0.00
23,Fireplaces,8288.0,0.00135,True,1.50,-0.08,0.00
1,LotFrontage,6066.0,0.00338,True,3.26,-0.08,0.00
20,BedroomAbvGr,7838.5,0.00615,True,1.05,-0.07,0.01

In [4]:
df['PoolQC_missing'] = df["PoolQC"].isna()
df['PoolQC_missing']

0       True
1       True
2       True
3       True
4       True
        ...
1455    True
1456    True
1457    True
1458    True
1459    True
Name: PoolQC_missing, Length: 1460, dtype: bool

In [5]:
from scipy.stats import chi2_contingency
categorical_col = 'Neighborhood'

# 3. Construir la tabla de contingencia (frecuencias cruzadas entre el nulo y las categorías)
contingency_table = pd.crosstab(df['PoolQC_missing'], df[categorical_col])
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)

print(f"Estadístico Chi2: {chi2_stat:.4f}")
print(f"Grados de libertad (dof): {dof}")
print(f"p-value: {p_value:.4f}")
print(f"Evidencia de MAR (p < 0.05): {p_value < 0.05}")

Estadístico Chi2: 23.1531
Grados de libertad (dof): 24
p-value: 0.5108
Evidencia de MAR (p < 0.05): False

In [6]:
# Si también quieres incluir booleanos:
categorical_cols = df.select_dtypes(include=['object', 'category', 'bool']).columns.tolist()
categorical_cols

C:\Users\albeiro\AppData\Local\Temp\ipykernel_20356\2586360863.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=['object', 'category', 'bool']).columns.tolist()

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition',
 'PoolQC_missing']