In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import probplot, mannwhitneyu
from IPython.display import display as dsp
%matplotlib inline
import sys, os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
from functions.eda_functions import test_mcar, list_missing_values, mannwhitneyu_method

PATH_DATASET = "../data/raw/train.csv"
df = pd.read_csv(PATH_DATASET)
print("dimensiones del dataset:", df.shape)
#display(df.head())

dimensiones del dataset: (1460, 81)

In [2]:
list_missing_values(df)

              missing counts  percentage(%)
PoolQC                  1453          99.52
MiscFeature             1406          96.30
Alley                   1369          93.77
Fence                   1179          80.75
MasVnrType               872          59.73
FireplaceQu              690          47.26
LotFrontage              259          17.74
GarageType                81           5.55
GarageYrBlt               81           5.55
GarageFinish              81           5.55
GarageQual                81           5.55
GarageCond                81           5.55
BsmtExposure              38           2.60
BsmtFinType2              38           2.60
BsmtQual                  37           2.53
BsmtCond                  37           2.53
BsmtFinType1              37           2.53
MasVnrArea                 8           0.55
Electrical                 1           0.07

In [ ]:
#PoolQC: Calidad de la piscina.
dsp(df['PoolQC'].unique())
#
resultado = mannwhitneyu_method(df, m="PoolQC", onlyTrue=True)
dsp(resultado.head(5))

<StringArray>
[nan, 'Ex', 'Fa', 'Gd']
Length: 4, dtype: str

    name_feature  value_mann_whitney_u  p_value  evidence_MAR
32      PoolArea                   0.0  0.00000          True
2        LotArea                1493.0  0.00125          True
23    Fireplaces                1883.0  0.00135          True
1    LotFrontage                1104.0  0.00338          True
20  BedroomAbvGr                2332.5  0.00615          True