In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display as dsp
%matplotlib inline
os.chdir('..')

df = pd.read_csv("./data/raw/train.csv")
use_df = df.copy()

In [2]:
from functions.utilsMethods import UtilsMethods
print(df.shape)

utils = UtilsMethods(use_df)
features_missing_values = utils.createFeaturesMissingValuesList()

(1460, 81)

              missing counts  percentage(%)     type
PoolQC                  1453          99.52      str
MiscFeature             1406          96.30      str
Alley                   1369          93.77      str
Fence                   1179          80.75      str
MasVnrType               872          59.73      str
FireplaceQu              690          47.26      str
LotFrontage              259          17.74  float64
GarageType                81           5.55      str
GarageYrBlt               81           5.55  float64
GarageFinish              81           5.55      str
GarageQual                81           5.55      str
GarageCond                81           5.55      str
BsmtExposure              38           2.60      str
BsmtFinType2              38           2.60      str
BsmtQual                  37           2.53      str
BsmtCond                  37           2.53      str
BsmtFinType1              37           2.53      str
MasVnrArea                 8           0.55  float64
Electrical                 1           0.07      str

In [3]:
from functions.numeric_missing_correlations import NumericMissingCorrelations
from functions.effect_size_and_direction import EffectSizeAndDirection
nmc = NumericMissingCorrelations(dataFrame=use_df)

In [6]:
""" 
PoolQC: Calidad de la piscina.

Ex	Excellent (Excelente)
Gd	Good (Bueno)
TA	Average/Typical (Promedio/Típico)
Fa	Fair (Justo/Regular)
NA	No Pool (Sin piscina)
"""
uniques = use_df["PoolQC"].unique()
print(uniques)

res = nmc.mannWhitneyU(featureMissingValues="PoolQC", effectSizeAndDirection=EffectSizeAndDirection.rank_biseral)  
res = res.apply(lambda x: x.round(4)).sort_values(by="p_value")
res[(res["evidence_MAR"]) & (res["p_value"] < 0.05) & (res["rankBiseral"].abs() > 0.1)]

<StringArray>
[nan, 'Ex', 'Fa', 'Gd']
Length: 4, dtype: str

,feature,stat,p_value,evidence_MAR,rankBiseral,diff_means,direction,interpretation
32,PoolArea,0.0,0.0000,True,1.0000,-555.0,negative,Grande
2,LotArea,1493.0,0.0012,True,0.7064,-7239.0,negative,Grande
23,Fireplaces,1883.0,0.0013,True,0.6297,0.0,negative,Grande
1,LotFrontage,1104.0,0.0034,True,0.6921,-51.0,negative,Grande
20,BedroomAbvGr,2332.5,0.0061,True,0.5413,-1.0,negative,Grande
12,1stFlrSF,2085.0,0.0070,True,0.5900,-306.0,negative,Grande
16,BsmtFullBath,2566.0,0.0082,True,0.4954,-1.0,negative,Mediano
15,GrLivArea,2178.0,0.0090,True,0.5717,-1325.0,negative,Grande
9,BsmtFinSF2,3485.5,0.0093,True,0.3146,0.0,negative,Mediano
14,LowQualFinSF,4444.0,0.0119,True,0.1261,0.0,negative,Pequeño
13,2ndFlrSF,2722.0,0.0188,True,0.4648,-950.0,negative,Mediano
22,TotRmsAbvGrd,2609.5,0.0231,True,0.4869,-2.0,negative,Mediano
36,SalePrice,2602.0,0.0257,True,0.4883,-72100.0,negative,Mediano
35,YrSold,7499.0,0.0265,True,0.4746,2.0,positive,Mediano
8,BsmtFinSF1,2672.0,0.0275,True,0.4746,-409.0,negative,Mediano
3,OverallQual,2732.0,0.0301,True,0.4628,-1.0,negative,Mediano

In [5]:
use_df[use_df['PoolQC'].notna()]['PoolArea'].median()

np.float64(555.0)