In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display as dsp
%matplotlib inline
os.chdir('..')

use_df = pd.read_csv("./data/raw/train.csv")

In [2]:
from functions.utilsMethods import UtilsMethods
print(use_df.shape)

utils = UtilsMethods(use_df)
features_missing_values = utils.createFeaturesMissingValuesList()
features_missing_values

(1460, 81)

              missingCounts  percentage(%)  presentCounts     type
PoolQC                 1453          99.52              7      str
MiscFeature            1406          96.30             54      str
Alley                  1369          93.77             91      str
Fence                  1179          80.75            281      str
MasVnrType              872          59.73            588      str
FireplaceQu             690          47.26            770      str
LotFrontage             259          17.74           1201  float64
GarageType               81           5.55           1379      str
GarageYrBlt              81           5.55           1379  float64
GarageFinish             81           5.55           1379      str
GarageQual               81           5.55           1379      str
GarageCond               81           5.55           1379      str
BsmtExposure             38           2.60           1422      str
BsmtFinType2             38           2.60           1422      str
BsmtQual                 37           2.53           1423      str
BsmtCond                 37           2.53           1423      str
BsmtFinType1             37           2.53           1423      str
MasVnrArea                8           0.55           1452  float64
Electrical                1           0.07           1459      str

Index(['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'MasVnrType', 'FireplaceQu',
       'LotFrontage', 'GarageType', 'GarageYrBlt', 'GarageFinish',
       'GarageQual', 'GarageCond', 'BsmtExposure', 'BsmtFinType2', 'BsmtQual',
       'BsmtCond', 'BsmtFinType1', 'MasVnrArea', 'Electrical'],
      dtype='str')

In [3]:
from functions.numeric_missing_correlations import NumericMissingCorrelations
from functions.effect_size_and_direction import EffectSizeAndDirection
from functions.test_normal_distribution import NormalDistributionTest
from functions.categorical_missing_correlations import CategoricalMissingCorrelations
nmc = NumericMissingCorrelations(dataFrame=use_df)
tnd = NormalDistributionTest(dataFrame=use_df)
cmc = CategoricalMissingCorrelations(dataFrame=use_df)

In [4]:
# PoolQC: Calidad de la piscina.
# Ex	Excellent (Excelente)
# Gd	Good (Bueno)
# TA	Average/Typical (Promedio/Típico)
# Fa	Fair (Justo/Regular)
# NA	No Pool (Sin piscina)

uniques = use_df["PoolQC"].unique()
print(f"Categorias presentes -> {uniques.tolist()}")

resPoolQC = nmc.mannWhitneyU(featureMissingValues="PoolQC",  effectSizeAndDirection=EffectSizeAndDirection.rank_biserial)  
resPoolQC = resPoolQC.apply(lambda x: x.round(5)).sort_values(by="p_value")
resPoolQC = resPoolQC[(resPoolQC["evidence_MAR"]) & (resPoolQC["p_value"] < 0.05) & (resPoolQC["rankBiseral"].abs() > 0.1)].reset_index(drop=True)
resPoolQC.iloc[0]

# ---------------------
# PoolQC vs PoolArea:
# p_value < 0.05 (valor -> 0.0)
# effect_size > 0.1 (valor -> 1.0)
# direction (valor -> -555.0)
# ---------------------
# El valor de p_value y effect_size son perfectos, se concluye que es un faltante estructural
# Estrategia:
#     - Se reemplaza missing values por categoria "NA"
# ---------------------
# La variable de relacion de nulos es numerica continua (LotArea)

Categorias presentes -> [nan, 'Ex', 'Fa', 'Gd']

feature           PoolArea
stat                   0.0
p_value                0.0
evidence_MAR          True
rankBiseral            1.0
diff_means          -555.0
direction         negative
interpretation      Grande
Name: 0, dtype: object

In [5]:
use_df["PoolQC"] = use_df["PoolQC"].fillna("NA")

In [6]:
# MiscFeature: Característica miscelánea no cubierta en otras categorías.
# 
# Elev	Elevator (Ascensor)
# Gar2	2nd Garage (if not described in garage section) (Segundo garaje (si no se describe en la sección de garaje))
# Othr	Other (Otro)
# Shed	Shed (over 100 SF) (Caseta (más de 100 pies cuadrados))
# TenC	Tennis Court (Cancha de tenis)
# NA	None (Ninguna)
uniquesMiscFeature = use_df["MiscFeature"].unique()
print(f"Unique values in MiscFeature: {uniquesMiscFeature}")

resMiscFeature = nmc.mannWhitneyU(featureMissingValues="MiscFeature",  effectSizeAndDirection=EffectSizeAndDirection.rank_biserial)
resMiscFeature = resMiscFeature.apply(lambda x: x.round(5)).sort_values(by="p_value")
resMiscFeature = resMiscFeature[(resMiscFeature["evidence_MAR"]) & (resMiscFeature["p_value"] < 0.05) & (resMiscFeature["rankBiseral"].abs() > 0.1)].reset_index(drop=True)
resMiscFeature.iloc[0]

# ---------------------
# MiscFeature vs MiscVal
# p_value < 0.05 (valor -> 0.0)
# effect_size > 0.1 (valor 0.963)
# direction -500.0
# ---------------------
# El valor de p_value y effect_size son perfectos, se concluye que es un faltante estructural
# Estrategia:
#     - Se reemplaza missing values por categoria "NA"
# ---------------------
# La variable de relacion de nulos es numerica continua (MiscVal)

Unique values in MiscFeature: <StringArray>
[nan, 'Shed', 'Gar2', 'Othr', 'TenC']
Length: 5, dtype: str

feature            MiscVal
stat                1406.0
p_value                0.0
evidence_MAR          True
rankBiseral        0.96296
diff_means          -500.0
direction         negative
interpretation      Grande
Name: 0, dtype: object

In [7]:
use_df['MiscFeature'] = use_df['MiscFeature'].fillna('NA')

In [8]:
# Alley: Tipo de acceso por callejón a la propiedad.
# Grvl	Gravel (Grava)
# Pave	Paved (Pavimentado)
# NA 	No alley access (Sin acceso por callejón)

uniquesAlley = use_df["Alley"].unique()
print(f"Unique values in Alley: {uniquesAlley}")

resAlley = nmc.mannWhitneyU(featureMissingValues="Alley",  effectSizeAndDirection=EffectSizeAndDirection.rank_biserial)
resAlley = resAlley.apply(lambda x: x.round(7)).sort_values(by="rankBiseral", ascending=False)
resAlley = resAlley[(resAlley["evidence_MAR"]) & (resAlley["p_value"] < 0.05) & (resAlley["rankBiseral"].abs() > 0.1)].reset_index(drop=True)
dsp(resAlley)

resAlletCat = cmc.g_test(featureMissingValues="Alley")
resAlletCat = resAlletCat[(resAlletCat["evidence_MAR"]) & (resAlletCat["p_value"] < 0.05)].apply(lambda x: x.round(7)).sort_values(by="p_value", ascending=True).reset_index(drop=True)
dsp(resAlletCat)

listFeaturesAlley = resAlley['feature'].unique().tolist()
print(listFeaturesAlley)

Unique values in Alley: <StringArray>
[nan, 'Grvl', 'Pave']
Length: 3, dtype: str

,feature,stat,p_value,evidence_MAR,rankBiseral,diff_means,direction,interpretation
0,LotFrontage,71623.0,0.000000e+00,True,0.493858,10.0,positive,Mediano
1,YearBuilt,90375.0,0.000000e+00,True,0.450887,50.0,positive,Mediano
2,TotalBsmtSF,87698.5,0.000000e+00,True,0.407918,244.0,positive,Mediano
3,BsmtFinSF1,85755.0,0.000000e+00,True,0.376717,405.0,positive,Mediano
4,1stFlrSF,84721.0,0.000000e+00,True,0.360117,162.0,positive,Mediano
5,LotArea,82102.5,4.000000e-07,True,0.318079,1450.0,positive,Mediano
6,MSSubClass,42711.0,2.000000e-07,True,0.314315,-20.0,negative,Mediano
7,SalePrice,81078.0,1.400000e-06,True,0.301632,25000.0,positive,Mediano
8,EnclosedPorch,43510.5,0.000000e+00,True,0.301479,0.0,negative,Mediano
9,WoodDeckSF,80222.5,7.000000e-07,True,0.287898,0.0,positive,Pequeño
10,GarageYrBlt,68157.5,1.830000e-05,True,0.281710,26.5,positive,Pequeño
11,MasVnrArea,77322.0,2.900000e-06,True,0.261576,0.0,positive,Pequeño
12,Fireplaces,78469.5,3.700000e-06,True,0.259755,1.0,positive,Pequeño
13,2ndFlrSF,46819.0,1.110000e-05,True,0.248364,-612.0,negative,Pequeño
14,BsmtFullBath,76053.5,3.670000e-05,True,0.220968,0.0,positive,Pequeño
15,GarageArea,74137.5,2.345700e-03,True,0.190209,40.0,positive,Pequeño
16,BsmtUnfSF,51484.5,5.520200e-03,True,0.173464,-189.0,negative,Pequeño
17,OverallCond,52541.0,5.535300e-03,True,0.156503,-1.0,negative,Pequeño
18,GarageCars,71767.5,6.580400e-03,True,0.152161,0.0,positive,Pequeño
19,OverallQual,71092.0,2.044580e-02,True,0.141316,0.0,positive,Pequeño

         feature        stat       p_value  evidence_MAR
0       MSZoning  155.383184  0.000000e+00          True
1   Neighborhood  269.335226  0.000000e+00          True
2     HouseStyle   54.828799  0.000000e+00          True
3    Exterior1st   99.864750  0.000000e+00          True
4    Exterior2nd  106.332054  0.000000e+00          True
5     Foundation   74.953875  0.000000e+00          True
6   GarageFinish   44.839979  0.000000e+00          True
7   BsmtFinType1   43.032185  0.000000e+00          True
8     CentralAir   30.423757  0.000000e+00          True
9     GarageType  111.416104  0.000000e+00          True
10    PavedDrive   46.439625  0.000000e+00          True
11  BsmtExposure   35.111078  1.000000e-07          True
12      BsmtQual   28.129448  3.400000e-06          True
13     RoofStyle   28.666513  2.700000e-05          True
14      LotShape   23.585638  3.050000e-05          True
15    GarageCond   23.115358  1.201000e-04          True
16     LotConfig   20.481047  4.012000e-04          True
17      BldgType   19.320035  6.799000e-04          True
18   LandContour   16.895178  7.427000e-04          True
19       Heating   20.923986  8.373000e-04          True
20    GarageQual   16.832149  2.083600e-03          True
21    Electrical   16.787165  2.125900e-03          True
22      BsmtCond   13.011286  4.612300e-03          True
23    Condition1   21.988264  4.937700e-03          True
24     HeatingQC   14.178680  6.746100e-03          True
25     ExterQual   10.719537  1.334330e-02          True
26  BsmtFinType2   13.885231  1.635510e-02          True

['LotFrontage', 'YearBuilt', 'TotalBsmtSF', 'BsmtFinSF1', '1stFlrSF', 'LotArea', 'MSSubClass', 'SalePrice', 'EnclosedPorch', 'WoodDeckSF', 'GarageYrBlt', 'MasVnrArea', 'Fireplaces', '2ndFlrSF', 'BsmtFullBath', 'GarageArea', 'BsmtUnfSF', 'OverallCond', 'GarageCars', 'OverallQual']

In [9]:
#Se imputa 'NoAlley' a los valores faltantes en la columna 'Alley'
use_df['Alley'] = use_df['Alley'].fillna('NoAlley')

In [10]:
"""
Fence: Calidad de la cerca.

GdPrv	Good Privacy (Buena privacidad)
MnPrv	Minimum Privacy (Privacidad mínima)
GdWo	Good Wood (Buena madera)
MnWw	Minimum Wood/Wire (Madera/alambre mínima)
NA	No Fence (Sin cerca)
"""
uniqueFence = use_df['Fence'].unique()
print(uniqueFence)

resFence = nmc.mannWhitneyU(featureMissingValues="Fence",  effectSizeAndDirection=EffectSizeAndDirection.rank_biserial)
resFence = resFence.apply(lambda x: x.round(7)).sort_values(by="rankBiseral", ascending=False)
resFence = resFence[(resFence["evidence_MAR"]) & (resFence["p_value"] < 0.05) & (resFence["rankBiseral"].abs() > 0.1)].reset_index(drop=True)
dsp(resFence)

<StringArray>
[nan, 'MnPrv', 'GdWo', 'GdPrv', 'MnWw']
Length: 5, dtype: str

,feature,stat,p_value,evidence_MAR,rankBiseral,diff_means,direction,interpretation
0,GarageYrBlt,205855.5,0.000000e+00,True,0.394638,23.0,positive,Mediano
1,YearBuilt,227330.0,0.000000e+00,True,0.372356,15.0,positive,Mediano
2,OverallQual,214073.0,0.000000e+00,True,0.292325,1.0,positive,Pequeño
3,SalePrice,213882.0,0.000000e+00,True,0.291172,31500.0,positive,Pequeño
4,FullBath,213569.5,0.000000e+00,True,0.289285,1.0,positive,Pequeño
5,YearRemodAdd,212947.5,0.000000e+00,True,0.285531,19.0,positive,Pequeño
6,GarageCars,207975.5,0.000000e+00,True,0.255515,0.0,positive,Pequeño
7,OverallCond,124452.0,0.000000e+00,True,0.248703,-1.0,negative,Pequeño
8,GarageArea,203304.5,0.000000e+00,True,0.227317,44.0,positive,Pequeño
9,GrLivArea,200083.5,1.000000e-07,True,0.207873,242.0,positive,Pequeño
10,BsmtUnfSF,198566.0,2.000000e-07,True,0.198712,132.0,positive,Pequeño
11,TotalBsmtSF,195573.5,2.500000e-06,True,0.180646,90.0,positive,Pequeño
12,OpenPorchSF,190414.0,4.330000e-05,True,0.149499,30.0,positive,Pequeño
13,MSSubClass,186339.0,7.815000e-04,True,0.124899,10.0,positive,Pequeño
14,BsmtFinSF2,145225.5,0.000000e+00,True,0.123297,0.0,negative,Pequeño
15,MasVnrArea,184654.0,3.380000e-04,True,0.122343,0.0,positive,Pequeño
16,TotRmsAbvGrd,184511.5,2.417000e-03,True,0.113867,0.0,positive,Pequeño
17,1stFlrSF,183395.0,5.205200e-03,True,0.107127,40.0,positive,Pequeño

In [11]:
use_df['Fence'] = use_df['Fence'].fillna('NoFence')

In [12]:
"""
MasVnrType: Tipo de revestimiento de mampostería.

BrkCmn	Brick Common (Ladrillo común)
BrkFace	Brick Face (Ladrillo visto)
CBlock	Cinder Block (Bloque de hormigón)
None	None (Ninguno) 
Stone	Stone (Piedra)
"""
uniqueMasVnrType = use_df['MasVnrType'].unique()
print(uniqueMasVnrType)

resMasVnrType = nmc.mannWhitneyU(featureMissingValues="MasVnrType",  effectSizeAndDirection=EffectSizeAndDirection.rank_biserial)
resMasVnrType = resMasVnrType.apply(lambda x: x.round(7)).sort_values(by="rankBiseral", ascending=False)
resMasVnrType = resMasVnrType[(resMasVnrType["evidence_MAR"]) & (resMasVnrType["p_value"] < 0.05) & (resMasVnrType["rankBiseral"].abs() > 0.1)].reset_index(drop=True)
dsp(resMasVnrType)

<StringArray>
['BrkFace', nan, 'Stone', 'BrkCmn']
Length: 4, dtype: str

,feature,stat,p_value,evidence_MAR,rankBiseral,diff_means,direction,interpretation
0,MasVnrArea,2151.0,0.000000e+00,True,0.991532,-202.5,negative,Grande
1,YearBuilt,132279.5,0.000000e+00,True,0.484025,-33.0,negative,Mediano
2,SalePrice,138723.5,0.000000e+00,True,0.458889,-49125.0,negative,Mediano
3,OverallQual,142285.5,0.000000e+00,True,0.444995,-2.0,negative,Mediano
4,TotalBsmtSF,151100.5,0.000000e+00,True,0.410611,-295.0,negative,Mediano
5,1stFlrSF,152854.5,0.000000e+00,True,0.403769,-291.5,negative,Mediano
6,GarageCars,155559.0,0.000000e+00,True,0.393220,0.0,negative,Mediano
7,GarageArea,157191.5,0.000000e+00,True,0.386852,-93.5,negative,Mediano
8,GarageYrBlt,146956.5,0.000000e+00,True,0.366367,-21.5,negative,Mediano
9,GrLivArea,177568.5,0.000000e+00,True,0.307369,-275.0,negative,Mediano
10,YearRemodAdd,181743.0,0.000000e+00,True,0.291085,-14.0,negative,Pequeño
11,FullBath,183376.0,0.000000e+00,True,0.284716,-1.0,negative,Pequeño
12,LotFrontage,125741.0,0.000000e+00,True,0.266342,-12.0,negative,Pequeño
13,BsmtFinSF1,189398.0,0.000000e+00,True,0.261226,-282.5,negative,Pequeño
14,TotRmsAbvGrd,192754.0,0.000000e+00,True,0.248136,-1.0,negative,Pequeño
15,Fireplaces,197038.0,0.000000e+00,True,0.231425,-1.0,negative,Pequeño
16,OpenPorchSF,200328.0,0.000000e+00,True,0.218592,-40.0,negative,Pequeño
17,WoodDeckSF,207774.5,0.000000e+00,True,0.189546,-120.0,negative,Pequeño
18,OverallCond,304002.5,0.000000e+00,True,0.185805,0.0,positive,Pequeño
19,LotArea,214099.0,1.000000e-07,True,0.164876,-1165.0,negative,Pequeño
20,EnclosedPorch,291861.0,0.000000e+00,True,0.138445,0.0,positive,Pequeño
21,BsmtFullBath,225103.5,3.800000e-06,True,0.121952,0.0,negative,Pequeño
22,HalfBath,228753.0,3.200000e-05,True,0.107716,0.0,negative,Pequeño