In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display as dsp
%matplotlib inline
os.chdir('..')

df = pd.read_csv("./data/raw/train.csv")
use_df = df.copy()

In [10]:
from functions.utilsMethods import UtilsMethods
print(df.shape)

utils = UtilsMethods(use_df)
features_missing_values = utils.createFeaturesMissingValuesList()
print(features_missing_values.tolist())

(1460, 81)

              missing counts  percentage(%)     type
PoolQC                  1453          99.52      str
MiscFeature             1406          96.30      str
Alley                   1369          93.77      str
Fence                   1179          80.75      str
MasVnrType               872          59.73      str
FireplaceQu              690          47.26      str
LotFrontage              259          17.74  float64
GarageType                81           5.55      str
GarageYrBlt               81           5.55  float64
GarageFinish              81           5.55      str
GarageQual                81           5.55      str
GarageCond                81           5.55      str
BsmtExposure              38           2.60      str
BsmtFinType2              38           2.60      str
BsmtQual                  37           2.53      str
BsmtCond                  37           2.53      str
BsmtFinType1              37           2.53      str
MasVnrArea                 8           0.55  float64
Electrical                 1           0.07      str

['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'MasVnrType', 'FireplaceQu', 'LotFrontage', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond', 'BsmtExposure', 'BsmtFinType2', 'BsmtQual', 'BsmtCond', 'BsmtFinType1', 'MasVnrArea', 'Electrical']

In [3]:
"""
#PoolQC: Calidad de la piscina.
Ex	Excellent (Excelente)
Gd	Good (Bueno)
TA	Average/Typical (Promedio/Típico)
Fa	Fair (Justo/Regular)
NA	No Pool (Sin piscina)
"""

from functions.numeric_missing_correlations import NumericMissingCorrelations

""" nmc = NumericMissingCorrelations(use_df)
res = nmc.mannWhitneyU(featureMissingValues="PoolQC", featuresReference=["PoolArea", "LotArea"])
dsp(res)
res = nmc.kolmogorovSmirnov(featureMissingValues="PoolQC", featuresReference=["PoolArea", "LotArea"])
dsp(res)
res = nmc.permutationTest(featureMissingValues="PoolQC", featuresReference=["PoolArea", "LotArea"])
dsp(res)
res = nmc.tStudent(featureMissingValues="PoolQC", featuresReference=["PoolArea", "LotArea"])
dsp(res) """

' nmc = NumericMissingCorrelations(use_df)\nres = nmc.mannWhitneyU(featureMissingValues="PoolQC", featuresReference=["PoolArea", "LotArea"])\ndsp(res)\nres = nmc.kolmogorovSmirnov(featureMissingValues="PoolQC", featuresReference=["PoolArea", "LotArea"])\ndsp(res)\nres = nmc.permutationTest(featureMissingValues="PoolQC", featuresReference=["PoolArea", "LotArea"])\ndsp(res)\nres = nmc.tStudent(featureMissingValues="PoolQC", featuresReference=["PoolArea", "LotArea"])\ndsp(res) '

In [4]:
from functions.categorical_missing_correlations import CategoricalMissingCorrelations
cmc = CategoricalMissingCorrelations(use_df)

In [5]:
cmc.g_test(featureMissingValues="PoolQC", featuresReference=["Fence"])

Empty DataFrame
Columns: [feature, stat, p_value]
Index: []

In [6]:
from functions.test_normal_distribution import NormalDistributionTest
utils.addFeatureNormalDistribution("chemicalRomance")
testNormal = NormalDistributionTest(use_df)
testNormal.shapiro_wilk_test(["chemicalRomance"])

      name_feature     stat  p_value  evidence_non_normality interpretacion
0  chemicalRomance  0.99871  0.36582                   False         Normal

In [7]:
testNormal.lilliefors_test()

       name_feature     stat  p_value  evidence_non_normality interpretacion
0        MSSubClass  0.19953  0.00100                    True      No normal
1       LotFrontage  0.10453  0.00100                    True      No normal
2           LotArea  0.25152  0.00100                    True      No normal
3       OverallQual  0.15515  0.00100                    True      No normal
4       OverallCond  0.32003  0.00100                    True      No normal
5         YearBuilt  0.12095  0.00100                    True      No normal
6      YearRemodAdd  0.17454  0.00100                    True      No normal
7        MasVnrArea  0.30953  0.00100                    True      No normal
8        BsmtFinSF1  0.16535  0.00100                    True      No normal
9        BsmtFinSF2  0.49916  0.00100                    True      No normal
10        BsmtUnfSF  0.09962  0.00100                    True      No normal
11      TotalBsmtSF  0.07595  0.00100                    True      No normal
12         1stFlrSF  0.08692  0.00100                    True      No normal
13         2ndFlrSF  0.35447  0.00100                    True      No normal
14     LowQualFinSF  0.53003  0.00100                    True      No normal
15        GrLivArea  0.06752  0.00100                    True      No normal
16     BsmtFullBath  0.38010  0.00100                    True      No normal
17     BsmtHalfBath  0.53905  0.00100                    True      No normal
18         FullBath  0.33371  0.00100                    True      No normal
19         HalfBath  0.40212  0.00100                    True      No normal
20     BedroomAbvGr  0.28146  0.00100                    True      No normal
21     KitchenAbvGr  0.53781  0.00100                    True      No normal
22     TotRmsAbvGrd  0.16744  0.00100                    True      No normal
23       Fireplaces  0.30178  0.00100                    True      No normal
24      GarageYrBlt  0.12750  0.00100                    True      No normal
25       GarageCars  0.31412  0.00100                    True      No normal
26       GarageArea  0.07534  0.00100                    True      No normal
27       WoodDeckSF  0.29518  0.00100                    True      No normal
28      OpenPorchSF  0.24064  0.00100                    True      No normal
29    EnclosedPorch  0.49781  0.00100                    True      No normal
30        3SsnPorch  0.52985  0.00100                    True      No normal
31      ScreenPorch  0.52701  0.00100                    True      No normal
32         PoolArea  0.52258  0.00100                    True      No normal
33          MiscVal  0.49931  0.00100                    True      No normal
34           MoSold  0.11879  0.00100                    True      No normal
35           YrSold  0.17088  0.00100                    True      No normal
36        SalePrice  0.12369  0.00100                    True      No normal
37  chemicalRomance  0.01955  0.23769                   False         Normal