In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import probplot, mannwhitneyu
from IPython.display import display as dsp
%matplotlib inline
os.chdir('..')
from functions.missingvalues.listMissingValues import list_missing_values

df = pd.read_csv("./data/raw/train.csv")
use_df = df.copy()

In [2]:
print(df.shape)
list_missing_values(use_df)

(1460, 81)

              missing counts  percentage(%)     type
PoolQC                  1453          99.52      str
MiscFeature             1406          96.30      str
Alley                   1369          93.77      str
Fence                   1179          80.75      str
MasVnrType               872          59.73      str
FireplaceQu              690          47.26      str
LotFrontage              259          17.74  float64
GarageType                81           5.55      str
GarageYrBlt               81           5.55  float64
GarageFinish              81           5.55      str
GarageQual                81           5.55      str
GarageCond                81           5.55      str
BsmtExposure              38           2.60      str
BsmtFinType2              38           2.60      str
BsmtQual                  37           2.53      str
BsmtCond                  37           2.53      str
BsmtFinType1              37           2.53      str
MasVnrArea                 8           0.55  float64
Electrical                 1           0.07      str

In [3]:
""" 
#PoolQC: Calidad de la piscina.
Ex	Excellent (Excelente)
Gd	Good (Bueno)
TA	Average/Typical (Promedio/Típico)
Fa	Fair (Justo/Regular)
NA	No Pool (Sin piscina)
"""
from functions.missingvalues.mannWhitney_u import MannWhitneyU
from functions.missingvalues.kolmogorovSmirnov import KolmogorovSmirnov
from functions.missingvalues.PermutationTest import PermutationTest
use_df['PoolQC'].unique()

mw = MannWhitneyU(use_df)
resmw = mw.all_features(missing_feature="PoolQC", desc=True, onlyTrue=True)
dsp(resmw)
ks = KolmogorovSmirnov(use_df)
resks = ks.all_features(missing_feature="PoolQC", desc=True, onlyTrue=True)
dsp(resks)
pt = PermutationTest(use_df)
ptss = pt.all_features(missing_feature="PoolQC", desc=True, onlyTrue=True)
dsp(ptss)

,reference_feature,stat,p_value,cohen_s,rho,p_value_interpretation,cohen_s_interpretation,rho_interpretation,p_value_rho
0,PoolArea,10171.0,0.00000,-99.84428,-1.00000,perfect!!,Grande (Negativa),Muy fuerte (Negativa),0.00000
1,LotArea,8678.0,0.00125,-1.26583,-0.08452,high,Grande (Negativa),Insignificante (Negativa),0.00123
2,Fireplaces,8288.0,0.00135,-1.50135,-0.08394,high,Grande (Negativa),Insignificante (Negativa),0.00133
3,LotFrontage,6066.0,0.00338,-3.25926,-0.08461,high,Grande (Negativa),Insignificante (Negativa),0.00334
4,BedroomAbvGr,7838.5,0.00615,-1.04669,-0.07174,high,Grande (Negativa),Insignificante (Negativa),0.00610
5,1stFlrSF,8086.0,0.00702,-2.14590,-0.07059,high,Grande (Negativa),Insignificante (Negativa),0.00697
6,BsmtFullBath,7605.0,0.00820,-1.11569,-0.06923,high,Grande (Negativa),Insignificante (Negativa),0.00814
7,GrLivArea,7993.0,0.00899,-2.79049,-0.06840,high,Grande (Negativa),Insignificante (Negativa),0.00894
8,BsmtFinSF2,6685.5,0.00930,-0.62695,-0.06812,high,Moderado (Negativa),Insignificante (Negativa),0.00923
9,LowQualFinSF,5727.0,0.01192,-1.03880,-0.06588,moderate,Grande (Negativa),Insignificante (Negativa),0.01181
10,2ndFlrSF,7449.0,0.01880,-1.30839,-0.06152,moderate,Grande (Negativa),Insignificante (Negativa),0.01873
11,TotRmsAbvGrd,7561.5,0.02307,-1.36341,-0.05950,moderate,Grande (Negativa),Insignificante (Negativa),0.02299
12,SalePrice,7569.0,0.02566,-1.36165,-0.05843,moderate,Grande (Negativa),Insignificante (Negativa),0.02558
13,YrSold,2672.0,0.02653,0.83445,0.05809,moderate,Grande (Positiva),Insignificante (Positiva),0.02645
14,BsmtFinSF1,7499.0,0.02747,-2.43937,-0.05773,moderate,Grande (Negativa),Insignificante (Negativa),0.02739
15,OverallQual,7439.0,0.03010,-1.07213,-0.05679,moderate,Grande (Negativa),Insignificante (Negativa),0.03002

,reference_feature,stat,p_value,cohen_s,rho,p_value_interpretation,cohen_s_interpretation,rho_interpretation,p_value_rho
0,PoolArea,1.00000,0.00000,-99.84428,-1.00000,very high,Grande (Negativa),Muy fuerte (Negativa),0.00000
1,LotArea,0.64340,0.00246,-1.26583,-0.08452,high,Grande (Negativa),Insignificante (Negativa),0.00123
2,GrLivArea,0.62413,0.00379,-2.79049,-0.06840,high,Grande (Negativa),Insignificante (Negativa),0.00894
3,LotFrontage,0.65774,0.00469,-3.25926,-0.08461,high,Grande (Negativa),Insignificante (Negativa),0.00334
4,1stFlrSF,0.55570,0.01502,-2.14590,-0.07059,moderate,Grande (Negativa),Insignificante (Negativa),0.00697

   reference_feature          stat  p_value   cohen_s      rho
0        LotFrontage     -77.16890   0.0002  -3.25926 -0.08461
1          GrLivArea   -1440.29899   0.0002  -2.79049 -0.06840
2           1stFlrSF    -820.88044   0.0002  -2.14590 -0.07059
3         BsmtFinSF1   -1097.47930   0.0002  -2.43937 -0.05773
4           PoolArea    -575.42857   0.0002 -99.84428 -1.00000
5        TotalBsmtSF    -960.17412   0.0006  -2.21336 -0.04722
6         Fireplaces      -0.96303   0.0008  -1.50135 -0.08394
7           2ndFlrSF    -569.02143   0.0018  -1.30839 -0.06152
8       TotRmsAbvGrd      -2.20706   0.0022  -1.36341 -0.05950
9          SalePrice -107733.90797   0.0072  -1.36165 -0.05843
10       OverallQual      -1.47921   0.0084  -1.07213 -0.05679
11        GarageArea    -222.94592   0.0094  -1.04511 -0.04253
12      BsmtFullBath      -0.57743   0.0104  -1.11569 -0.06923
13      BedroomAbvGr      -0.85193   0.0160  -1.04669 -0.07174
14           LotArea  -12590.82460   0.0368  -1.26583 -0.08452
15            YrSold       1.10677   0.0372   0.83445  0.05809
16        WoodDeckSF    -111.86324   0.0414  -0.89388 -0.05013