In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import probplot, mannwhitneyu
from IPython.display import display as dsp
%matplotlib inline
os.chdir('..')

df = pd.read_csv("./data/raw/train.csv")
from functions.eda_functions import NormalDistributionTest, list_missing_values

In [4]:
list_missing_values(df)
testNormalize = NormalDistributionTest(df)
testNormalize.jarque_bera(['PoolArea'])

              missing counts  percentage(%)
PoolQC                  1453          99.52
MiscFeature             1406          96.30
Alley                   1369          93.77
Fence                   1179          80.75
MasVnrType               872          59.73
FireplaceQu              690          47.26
LotFrontage              259          17.74
GarageType                81           5.55
GarageYrBlt               81           5.55
GarageFinish              81           5.55
GarageQual                81           5.55
GarageCond                81           5.55
BsmtExposure              38           2.60
BsmtFinType2              38           2.60
BsmtQual                  37           2.53
BsmtCond                  37           2.53
BsmtFinType1              37           2.53
MasVnrArea                 8           0.55
Electrical                 1           0.07

,name_feature,jb_stat,p_value,skewness,kurtosis,normal,evidence_non_normality,interpretacion
0,PoolArea,3.065038e+06,0.0,14.813135,222.500507,False,True,No normal

In [3]:
normal_df = pd.DataFrame(np.random.randn(100000))
normal_df.columns = ['numeros']
cn = NormalDistributionTest(normal_df)
cn.shapiro_wilk_test()

/home/elole/projects/ML-house-prices/ml-house/lib/python3.14/site-packages/scipy/stats/_axis_nan_policy.py:601: UserWarning: scipy.stats.shapiro: For N > 5000, computed p-value may not be accurate. Current N is 100000.
  res = hypotest_fun_out(*samples, **kwds)

  name_feature  shapiro_stat  p_value  evidence_non_normality interpretacion
0      numeros      0.999979  0.88463                   False         Normal